name: Build and Publish
on:
  push:
    branches:
    - "**"
      # - main

env:
  ZIG_VERSION: 0.14.1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            install-deps: |
              version="zig-x86_64-linux-$ZIG_VERSION"
              echo "$version"
              uri="https://ziglang.org/download/$ZIG_VERSION/$version.tar.xz"
              curl $uri -o zig-linux.tar.xz
              tar -xf zig-linux.tar.xz 
              rm zig-linux.tar.xz
              mv $version zig
              echo "Zig installed"
              echo "$PWD/zig/" >> $GITHUB_PATH
              ./zig/zig version
          - os: windows-latest
            install-deps: |
              $version = "zig-x86_64-windows-$env:ZIG_VERSION"
              Write-Output $version
              $uri = "https://ziglang.org/download/$env:ZIG_VERSION/$version.zip"
              Invoke-WebRequest -Uri "$uri" -OutFile ".\zig-windows.zip"
              Expand-Archive -Path ".\zig-windows.zip" -DestinationPath ".\" -Force
              Remove-Item -Path ".\zig-windows.zip"
              Rename-Item -Path ".\$version" -NewName ".\zig"
              Write-Host "Zig installed."
              Add-Content -Path $env:GITHUB_ENV -Value "PATH=.\zig\`;$env:PATH"
              .\zig\zig.exe version
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare
        run: |
          ${{ matrix.install-deps }}

      - name: Build web assets
        if: runner.os == 'Linux'
        run: |
          cd path/to/your/project
          npm ci
          npm run build
          mkdir -p $GITHUB_WORKSPACE/zig-out/dist
          cp -r dist/* $GITHUB_WORKSPACE/zig-out/dist/
          
      - name: Build web assets (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd path\to\your\project
          npm ci
          npm run build
          New-Item -ItemType Directory -Force -Path $env:GITHUB_WORKSPACE\zig-out\dist
          Copy-Item -Path .\dist\* -Destination $env:GITHUB_WORKSPACE\zig-out\dist -Recurse -Force

      - name: Build executable
        run: zig build --release=small 

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-zig-binary
          path: zig-out/bin/*

