name: Lint and Test
on:
  - push
  - pull_request
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
        include:
          - os: windows-latest
            install-deps: |
              $zigVersion = "0.14.1"
              $version = "zig-x86_64-windows-$zigVersion"
              Write-Output $version
              $uri = "https://ziglang.org/download/$zigVersion/$version.zip"
              Invoke-WebRequest -Uri "$uri" -OutFile ".\zig-windows.zip"
              Expand-Archive -Path ".\zig-windows.zip" -DestinationPath ".\" -Force
              Remove-Item -Path ".\zig-windows.zip"
              Rename-Item -Path ".\$version" -NewName ".\zig"
              Write-Host "Zig installed."
              Add-Content -Path $env:GITHUB_ENV -Value "PATH=.\zig\`;$env:PATH"
              .\zig\zig.exe version
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          ${{ matrix.install-deps }}
      - name: Run tests
        run: |
          zig build test --summary all
