name: Lint and Test
on:
  - push
  - pull_request
env:
  ZIG_VERSION: 0.14.1
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install zlint
        run: curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/heads/main/tasks/install.sh | bash

      - name: Run zlint
        run: zlint

      - name: Run eslint
        run: |
          cd client/protonexus
          npm ci
          npm run lint

  unit_tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            install-deps: |
              version="zig-x86_64-linux-$ZIG_VERSION"
              echo "$version"
              uri="https://ziglang.org/download/$ZIG_VERSION/$version.tar.xz"
              curl $uri -o zig-linux.tar.xz
              tar -xf zig-linux.tar.xz 
              rm zig-linux.tar.xz
              mv $version zig
              echo "Zig installed"
              echo "$PWD/zig/" >> $GITHUB_PATH
              ./zig/zig version
          - os: windows-latest
            install-deps: |
              $version = "zig-x86_64-windows-$env:ZIG_VERSION"
              Write-Output $version
              $uri = "https://ziglang.org/download/$env:ZIG_VERSION/$version.zip"
              Invoke-WebRequest -Uri "$uri" -OutFile ".\zig-windows.zip"
              Expand-Archive -Path ".\zig-windows.zip" -DestinationPath ".\" -Force
              Remove-Item -Path ".\zig-windows.zip"
              Rename-Item -Path ".\$version" -NewName ".\zig"
              Write-Host "Zig installed."
              Add-Content -Path $env:GITHUB_ENV -Value "PATH=.\zig\`;$env:PATH"
              .\zig\zig.exe version
          - os: macos-latest
            install-deps: |
              version="zig-x86_64-macos-$ZIG_VERSION"
              echo "$version"
              uri="https://ziglang.org/download/$ZIG_VERSION/$version.tar.xz"
              curl $uri -o zig-macos.tar.xz
              tar -xf zig-macos.tar.xz 
              rm zig-macos.tar.xz
              mv $version zig
              echo "Zig installed"
              echo "$PWD/zig/" >> $GITHUB_PATH
              ./zig/zig version
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Prepare
        run: |
          ${{ matrix.install-deps }}
      - name: Run tests
        run: |
          zig build test --summary all
